### ISSUE TITLE
Outdated Env, TransportTorus1D? Maybe missing some supporting code.

### ISSUE THREAD

**Issue by DanielTakeshi** [Xingyu-Lin/softgym#11]
Hello,

Just to quickly check is the TransportTorus1D environment used at all?

https://github.com/Xingyu-Lin/softgym/blob/master/softgym/envs/transport_torus.py

This seems to import the `softgym.envs.fluid_rigid_env` package:

https://github.com/Xingyu-Lin/softgym/blob/3841d5c9f4d13277136776054853aad61e28c848/softgym/envs/transport_torus.py#L4-L13

However I don't see this file implemented in the repository.

This environment is also not reported in the paper so I'm guessing it's an older environment. However if there is some supporting code that could make this usable, it might be good to have it in this repository.

**Comment by yufeiwang63** [comment]
yes this is an outdated env. This env is to transport a rigid torus to a target location. Since it is not about deformable object manipulation we did not include it in the final version. If you feel strongly interested in using it, we will certainly consider cleaning and release the env later.

**Comment by DanielTakeshi** [comment]
Thanks for the explanation. It seems like it's a low priority, and I probably won't use it. I'll close this issue.
