### ISSUE TITLE
FileNotFoundError: .pkl File Not Found

### ISSUE THREAD

**Issue by LovelyBuggies** [Xingyu-Lin/softgym#12]
Hello developers,

I am building sofygym on my machine (ubuntu 18.04) with cuda 11. Following the instructions of @FranBesq, I was trying to run the random_env.py outside docker (but compile in docker). All steps worked expect the FileNotFoundError when running it. Here's my commands:

Inside docker:
```bash
sudo nvidia-docker run \
  -v /home/nino/softgym:/home/nino/softgym \
  -v /home/nino/anaconda3:/home/nino/anaconda3 \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  --gpus all \
  -e DISPLAY=$DISPLAY \
  -e QT_X11_NO_MITSHM=1 \
  -it xingyu/softgym:latest bash

cd home/nino/softgym
export PATH="/home/nino/anaconda3/bin:$PATH"
export PYFLEXROOT=${PWD}/PyFlex
export PYTHONPATH=${PYFLEXROOT}/bindings/build:$PYTHONPATH
export LD_LIBRARY_PATH=${PYFLEXROOT}/external/SDL2-2.0.4/lib/x64:$LD_LIBRARY_PATH

conda create -n softgym
conda activate softgym
./compile_1.0.sh
```

Outside docker
```bash
Ctrl+D
cd home/nino/softgym
export PATH="/home/nino/anaconda3/bin:$PATH"
export PYFLEXROOT=${PWD}/PyFlex
export PYTHONPATH=${PYFLEXROOT}/bindings/build:$PYTHONPATH
export LD_LIBRARY_PATH=${PYFLEXROOT}/external/SDL2-2.0.4/lib/x64:$LD_LIBRARY_PATH
python3 examples/random_env.py --env_name RopeConfiguration --headless 1
```

I met this **error**:

```bash
FileNotFoundError: No such file or dictionary: 'home/nino/softgym/softgym/envs/../files/rope_configuration.pkl'.
```

I looked in the files, there is no such pkl file. Do you know why?

**Comment by yufeiwang63** [comment]
For ropeconfiguration, you need to first download this pickle file here: https://drive.google.com/file/d/1f3FK_7gwnJLVm3VaSacvYS7o-19-XPrr/view

**Comment by LovelyBuggies** [comment]
Thanks, I see I have another try on pouring water environment, which also throws a "FileNotfoundError: the directory '/home/nino/softgym/data' does not exist". Should there exist such a folder?

**Comment by LovelyBuggies** [comment]
Thank you for help, it works!
