### ISSUE TITLE
/usr/bin/ld: cannot find -lEGL when running compile

### ISSUE THREAD

**Issue by rehaanahmad2013** [Xingyu-Lin/softgym#15]
I have an error when running . ./compile_1.0.sh 
Everything runs normally up until the last step where it is working with pyflex, in which I get the following error: 
![pyflexerror](https://user-images.githubusercontent.com/34905129/124221088-dc99cc00-dab3-11eb-8d5b-d1e2ff271a35.PNG)
If I go to python, I can "import softgym". The only issue is with importing pyflex due to this error above.
Any idea of what I can do to fix this? I'm running Ubuntu 16.04 and CUDA 10.0

**Comment by rehaanahmad2013** [comment]
Also, to follow up I have nvidia driver 440.44

**Comment by Xingyu-Lin** [comment]
Did you add `/usr/lib` in your PATH? You can try to debug the issue by compiling a simple c++ program that uses EGL.

**Comment by rehaanahmad2013** [comment]
@Xingyu-Lin Thanks for the response. I did try adding /usr/lib to PATH as well as a couple other variations to no avail. I think your response in issue #1 provides some insight, as there is a libEGL.so file there in nvidia-440. If I can locate that nvidia-440 folder and then add that to the path, perhaps the issue will be solved.
