### ISSUE TITLE
Adding Static Objects

### ISSUE THREAD

**Issue by wilson1yan** [Xingyu-Lin/softgym#17]
Is there a way to add static objects into the scene? i.e. immovable objects such as thin cylinders or rectangles that a rope or cloth can collide with?

**Comment by wilson1yan** [comment]
Nevermind, it seems to be doable with just `add_box`, it seems that separate code is need to handle the collisions well.

**Comment by Barbany** [comment]
@wilson1yan Could you please post your solution to add a box that handles collisions?
