### ISSUE TITLE
Modifying rendering

### ISSUE THREAD

**Issue by zaynahjaved** [Xingyu-Lin/softgym#18]
Hi! Is there a way to easily modify the appearance of the rendered gifs? For example, if I wanted to have the pickers not show in the image and also change the color of the cloth/fluid/rope?

**Comment by Xingyu-Lin** [comment]
The easiest way for removing picker is to move the picker out of the camera before rendering and then move it back after that. You can also disable the shape rendering function in pyflex.cpp. That would be more principled but requires more digging into the c++ code. To change the color, you need to modify the opengl shader in the c++ code. We don't have a python API to do that right now. We have one API for change the color of the shape, as an example: https://github.com/Xingyu-Lin/softgym/blob/27c6cbc69692ce3d1d5095847f0fcca1f8193714/PyFlex/bindings/pyflex.cpp#L779

**Comment by zaynahjaved** [comment]
Thanks! I have an additional question, is there a way to modify how close the particles are together? I know we can modify the radius of the particle but this in turn modifies the number of particles (and therefore the dimension of the cloth in cloth_env)

**Comment by yufeiwang63** [comment]
If you want to directly change the cloth size, i.e., width and length, you can change this line here: https://github.com/Xingyu-Lin/softgym/blob/master/softgym/envs/cloth_env.py#L58
If you want to change the distance between particles when creating the cloth, see this function here which essentially creates the cloth as a spring grid: https://github.com/Xingyu-Lin/softgym/blob/master/PyFlex/bindings/helpers.h#L848.
[This line ](https://github.com/Xingyu-Lin/softgym/blob/master/PyFlex/bindings/helpers.h#L858) controls how particles are spatially added. It currently mostly just depends on the particle radius. You can modify the code here to add some additional distance between particles. After the change, you also need to recompile PyFlex to make sure it takes effects.
