### ISSUE TITLE
Action_mode?

### ISSUE THREAD

**Issue by wangZHEN000000** [Xingyu-Lin/softgym#19]
Hi, how can I use the franka robot in the ClothFlatten environment?

**Comment by Xingyu-Lin** [comment]
Unfortunately, after communicating with Nvidia, we are unable to release the softgym-robot part of the code to the public, which requires FleXRobotics.

**Comment by sirkrisp** [comment]
Hi Xingyu, I am also interested in using the robot arm within softgym. Therefore, I might re-implement FleXRobotics. Besides robot URDF loading and some control, is there any other function that FleXRobotics has? Also, to avoid confusion, it might be helpful to list this limitation in the README.

Edit: On a second thought, I guess it would make more sense to get in touch with Nvidia and ask for access to the code.
