### ISSUE TITLE
Missing Dependency/ Python Package from environment.yaml

### ISSUE THREAD

**Issue by DhananjayAshok** [Xingyu-Lin/softgym#2]
Hi there, I was trying to run the example from the readme and got the message

>> python examples/random_env.py --env_name PassWater
Traceback (most recent call last):
  File "examples/random_env.py", line 5, in <module>
    from softgym.registered_env import env_arg_dict, SOFTGYM_ENVS
  File "/h/ashokdha/projects/softgym/softgym/registered_env.py", line 1, in <module>
    from softgym.envs.pour_water import PourWaterPosControlEnv
  File "/h/ashokdha/projects/softgym/softgym/envs/pour_water.py", line 8, in <module>
    from shapely.geometry import Polygon
ModuleNotFoundError: No module named 'shapely'

I installed shapely into my conda environment and this went away. I think there may be a missing dependency for this in the environments.yaml file? 

Thank You,
Dhananjay

**Comment by Xingyu-Lin** [comment]
Thanks for posting this issue! I have updated environments.yaml
