### ISSUE TITLE
Running SoftGym on Cluster With Multipe GPUs

### ISSUE THREAD

**Issue by rehaanahmad2013** [Xingyu-Lin/softgym#21]
Hi,

I'm trying to run the softgym examples on a cluster with the exact same setup as a remote workstation I have setup that works just fine with SoftGym (cuda 9.0, 440.44 driver, 16.04 ubuntu).

The cluster has multiple gpus but I am only given access to one of the gpus. So if some program attempts to render and access any of the other gpus it will cause an openGL error. For example, when running headless rendering with MuJoCo I have to put "export GPUS=$SLURM_JOB_GPUS" and set "CUDA_VISIBLE_DEVICES" for it to work.

I have these above variables set (also tried setting 'NVIDIA_VISIBLE_DEVICES') but I am getting an openGL error when running softgym and I heavily suspect it has something to do with it attempting to access a GPU on the cluster it does not have access to. 

Is there some other variables besides 'GPUS' and 'CUDA_VISIBLE_DEVICES' I would need to set here?

**Comment by yufeiwang63** [comment]
Previously we tried `export EGL_GPU=$SLURM_JOB_GRES` to make sure softgym is using the allocated GPU from slurm.

**Comment by rehaanahmad2013** [comment]
Perfect. That does the trick, thank you!

**Comment by Xingyu-Lin** [comment]
issue resolved
