### ISSUE TITLE
About action repeat

### ISSUE THREAD

**Issue by ShiguangSun** [Xingyu-Lin/softgym#26]
Hi，  I have a question about 'action repeat'. Why set the 'action repeat' ‘8‘’? Usually, ‘4’ is more common. And if I choose observation_mode 'key_point', do I still need to set ‘action repeat’ ‘8’？ Thanks！

**Comment by yufeiwang63** [comment]
There is no specific reason, but mostly to ensure that the task can be finished with the chosen action_repeat and time horizon. If you change action_repeat to be 4, then you might need to scale task horizon to be twice.
The observation mode only affects your observation, and I don't see how it should affect the action_repeat
