### ISSUE TITLE
CudaSetupArgument

### ISSUE THREAD

**Issue by TriBall3** [Xingyu-Lin/softgym#27]
After I install Docker, execute the following command:

export PATH="PATH_TO_CONDA/bin:$PATH"
. ./prepare_1.0.sh && ./compile_1.0.sh

To appear:
[100%] Linking CXX shared module pyflex.cpython-36m-x86_64-linux-gnu.so
[100%] Built target pyflex

I think so far no problem then when I run:
python examples/random_env.py --env_name PassWater

There's a problem:
![image](https://user-images.githubusercontent.com/75004709/149865917-a03e50fc-6b5c-46e6-90d4-c378ba0ff561.png)

Can you help me solve this problem?Thank you very much!

**Comment by hongtaowu67** [comment]
Did you have this problem resolved? If so, how did you solve it? Thanks! @TriBall3

**Comment by DanielTakeshi** [comment]
@hongtaowu67 I would recommend starting a new GitHub issue and showing your exact steps to reproduce the error.

**Comment by hongtaowu67** [comment]
Thanks. I have initiated an issue at #38.
