### ISSUE TITLE
Segmentation Fault (core dumped) while running headless

### ISSUE THREAD

**Issue by halid1020** [Xingyu-Lin/softgym#29]
Hi, I am running softgym inside your given docker. It works well without the headless flag, But it reports segmentation fault when  I want to run it headless, i.e.,  `python examples/random_env.py --env_name ClothFlatten --headless 1 `. Could you please help me with this?

**Comment by halid1020** [comment]
I think I fixed the problem by running the program outside the docker, as I did not know docker is just for compilation.

**Comment by zcswdt** [comment]
> 通过在 docker 之外运行程序解决了这
哈喽，请问你在什么系统成功运行了呢，我现在遇到问题也是这个，能告知一下吗？谢谢
