### ISSUE TITLE
fatal error: EGL/eglplatform.h: No such file or directory

### ISSUE THREAD

**Issue by BOBaraki** [Xingyu-Lin/softgym#3]
Hello,

When I try to compile the pyflex I get the following:

`[  5%] Building CXX object CMakeFiles/pyflex.dir/imgui.cpp.o
[ 10%] Building CXX object CMakeFiles/pyflex.dir/shadersDemoContext.cpp.o
[ 15%] Building CXX object CMakeFiles/pyflex.dir/opengl/imguiRenderGL.cpp.o
[ 21%] Building CXX object CMakeFiles/pyflex.dir/home/tzortzis/softgym/PyFlex/core/tga.cpp.o
[ 31%] Building CXX object CMakeFiles/pyflex.dir/home/tzortzis/softgym/PyFlex/core/pfm.cpp.o
[ 36%] Building CXX object CMakeFiles/pyflex.dir/home/tzortzis/softgym/PyFlex/core/mesh.cpp.o
[ 42%] Building CXX object CMakeFiles/pyflex.dir/home/tzortzis/softgym/PyFlex/core/extrude.cpp.o
[ 31%] Building CXX object CMakeFiles/pyflex.dir/home/tzortzis/softgym/PyFlex/core/aabbtree.cpp.o
[ 47%] Building CXX object CMakeFiles/pyflex.dir/home/tzortzis/softgym/PyFlex/core/platform.cpp.o
[ 57%] Building CXX object CMakeFiles/pyflex.dir/pyflex.cpp.o
[ 57%] Building CXX object CMakeFiles/pyflex.dir/opengl/shadersGL.cpp.o
[ 63%] Building CXX object CMakeFiles/pyflex.dir/home/tzortzis/softgym/PyFlex/core/sdf.cpp.o
[ 68%] Building CXX object CMakeFiles/pyflex.dir/home/tzortzis/softgym/PyFlex/core/perlin.cpp.o
[ 73%] Building CXX object CMakeFiles/pyflex.dir/opengl/shader.cpp.o
[ 78%] Building CXX object CMakeFiles/pyflex.dir/home/tzortzis/softgym/PyFlex/core/maths.cpp.o
[ 84%] Building CXX object CMakeFiles/pyflex.dir/home/tzortzis/softgym/PyFlex/core/core.cpp.o
[ 89%] Building CXX object CMakeFiles/pyflex.dir/home/tzortzis/softgym/PyFlex/core/png.cpp.o
[ 94%] Building CXX object CMakeFiles/pyflex.dir/home/tzortzis/softgym/PyFlex/core/voxelize.cpp.o
In file included from /home/tzortzis/softgym/PyFlex/bindings/opengl/../../external/glad/src/glad_egl.c:160:0,
                 from /home/tzortzis/softgym/PyFlex/bindings/opengl/shadersGL.cpp:39:
/home/tzortzis/softgym/PyFlex/bindings/opengl/../../external/glad/src/../include/glad/glad_egl.h:199:10: fatal error: EGL/eglplatform.h: No such file or directory
 #include <EGL/eglplatform.h>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
`

There are other warning after than but the error I believe is here since it terminates the compilation. Do you have a solution for this??

Thanks

**Comment by Xingyu-Lin** [comment]
It seems to be related to EGL installation. Maybe try installing the following packages:
```apt-get install libglfw3 libgles2-mesa-dev```

**Comment by BOBaraki** [comment]
It worked. Thanks a lot! :D

**Comment by zhangp11** [comment]
fedora34:dnf install libgle-devel.x86_64 libgle.x86_64可以解决
