### ISSUE TITLE
Can the simulater segment the object?

### ISSUE THREAD

**Issue by ShiguangSun** [Xingyu-Lin/softgym#31]
Hi, I have a question. I want to get the observed image with only objects (like rope, cloth), is there a way to segment the objects in the image？
Thank you for any help you can offer!

**Comment by Murkey8895** [comment]
It seems that "pyflex.render_cloth()" is useful.

**Comment by ShiguangSun** [comment]
> It seems that "pyflex.render_cloth()" is useful.
I just tried the way you said, but it seems can't work. It shows: 
AttributeError: module 'pyflex' has no attribute 'render_cloth'
Can you use this? Any details to pay attention to?

**Comment by Murkey8895** [comment]
> > It seems that "pyflex.render_cloth()" is useful.
> > I just tried the way you said, but it seems can't work. It shows:
> > AttributeError: module 'pyflex' has no attribute 'render_cloth'
> > Can you use this? Any details to pay attention to?

You can refer to the example code in random_env.py:
https://github.com/Xingyu-Lin/softgym/blob/bb383f64cd488062587714abbae38f27ed9f2457/examples/random_env.py#L18

**Comment by ShiguangSun** [comment]
> > > It seems that "pyflex.render_cloth()" is useful.
> > > I just tried the way you said, but it seems can't work. It shows:
> > > AttributeError: module 'pyflex' has no attribute 'render_cloth'
> > > Can you use this? Any details to pay attention to?
> 
> You can refer to the example code in random_env.py:
> 
> https://github.com/Xingyu-Lin/softgym/blob/bb383f64cd488062587714abbae38f27ed9f2457/examples/random_env.py#L18

Ok, I saw it, this is the new version feature, I am using the old version. I will try this. Thanks!
