### ISSUE TITLE
Cannot create new env after calling env.close() 

### ISSUE THREAD

**Issue by alissamueller** [Xingyu-Lin/softgym#32]
Hey,

so while working with softgym, I encountered the following issue: When I close an environment via env.close() (and pyflex.clean() is called), I cannot create a new environment afterwards. Here is some code to recreate the issue. If I comment out the env.close() line, it works just fine, but if env.close() was called, it crashes during the first pyflex.set_scene() call within the environment. I need the env.close() to work in order to use AsyncVectorEnvs from gym.

    
```
from softgym.envs.pass_water import PassWater1DEnv

def main():
    env = PassWater1DEnv(observation_mode="key_point", action_mode="direct", headless=True, use_cached_states=False)


    env.close()

    env = PassWater1DEnv(observation_mode="key_point", action_mode="direct", headless=True, use_cached_states=False)

if __name__ == '__main__':
    main()
```

Console Output:
```
Compute Device: NVIDIA GeForce RTX 2070

Pyflex init done!
pass water generate env variations 0
generate env variation: medium volume water
stablize water!
1 config and state pairs generated and saved to /home/softgym/softgym/envs/../cached_initial_states/pass_water_init_states.pkl
Compute Device: NVIDIA GeForce RTX 2070

Pyflex init done!
pass water generate env variations 0
generate env variation: large volume water

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

Thanks in advance for any help you can offer!

**Comment by yufeiwang63** [comment]
Yes, there are some issues with env.close() right now. Perhaps you can wrap a new env.close() function, e.g., an empty function, to override the current one, so it can work with AsyncVectorEnvs?
The previous env will be closed automatically when calling pyflex.set_scene() again, so actually there is no need to explicitly call env.close().

**Comment by alissamueller** [comment]
Thanks for your quick answer! Yeah I thought of wrapping an empty close function as well, but it's nice to hear that the previous env will be cleaned up automatically and that the close() problems aren't due to my machine setup or something.

Seems to work fine for now with the empty close function
