### ISSUE TITLE
How to assign a certain GPU for softgym?

### ISSUE THREAD

**Issue by ShiguangSun** [Xingyu-Lin/softgym#33]
Hi,
I have a new question here. Softgym seems to automatically use available gpus. How to assign a certain GPU for softgym?
Thank you for any suggestions!

**Comment by ShiguangSun** [comment]
Hi,
I have a new question here. Softgym seems to automatically use available gpus. How to assign a certain GPU for softgym?
Thank you for any suggestions!

**Comment by yufeiwang63** [comment]
You can use 
```
export CUDA_VISIBLE_DEVICES=X
export EGL_GPU=X
```
to choose the GPUs you want to use.

**Comment by ShiguangSun** [comment]
> 

Thanks for reply so quickly!
