### ISSUE TITLE
Modifying Cloth Scene Visuals

### ISSUE THREAD

**Issue by rlee3359** [Xingyu-Lin/softgym#37]
Hi, thanks for all your great work on this. I just wanted to ask about modifying the visuals of the cloth scenes.

Firstly, I noticed that the "Folding" environments have a cloth with a stripe down the side in the secondary colour, while the "Flatten" and "Drop" environments are just plain cloths with two sides. I dug around in the environments but I wasn't sure what determines this. Is there something stored in the "configs" or "cached states" that modifies this attribute? Essentially I'd like to just create an env with top down grasping, starting with from a flat configuration (for now), with a simple one colour, plain cloth.

The folding env cloth looks like this:
![fold_env](https://user-images.githubusercontent.com/15622840/168225432-c694aed8-8147-46e9-b4aa-b9245524b0a2.png)

While the flatten cloth looks like this:
![flatten_env](https://user-images.githubusercontent.com/15622840/168225457-a6f51d5b-cce8-4410-b5b5-a60564d53d55.png)

Additionally, is it possible to change the background/table at all? Again I would like to just replace the grid pattern with a plain surface if possible.

Thanks again!

**Comment by Xingyu-Lin** [comment]
The strip was added in here: https://github.com/Xingyu-Lin/softgym/blob/master/PyFlex/bindings/softgym_scenes/softgym_cloth.h and can be turned off by setting the flip_mesh.

For the backround color, maybe you can search for any usage of the DrawPlanes function and turn it off

**Comment by rlee3359** [comment]
Thanks very much! Setting flip_mesh to 0 and disabling DrawPlanes did the trick.
