### ISSUE TITLE
Wrong versions of dependencies?

### ISSUE THREAD

**Issue by yordanh** [Xingyu-Lin/softgym#4]
While installing things through pip, opencv-python and cmake come back as wrong versions. Indeed according to pypi.org there are no

**opencv-python==5.1.1
cmake==3.14.0**

Wonder if conda has different version name conventions or it's just a mistake in the spec.

**Comment by yufeiwang63** [comment]
Yes, seems that is an error for the environment.yml. Please use the updated environment.yml file for installation. It is also copied here for your convenience.

name: softgym
channels:
  - defaults
dependencies:
  - numpy=1.17.2
  - imageio=2.6.1
  - glob2=0.7
  - cmake=3.14.0
  - pybind11=2.4.3
  - click
  - matplotlib
  - joblib
  - Pillow=6.1
  - plotly=2.0
  - pip:
    - gtimer
    - gym==0.14.0
    - moviepy
    - opencv-python==4.1.1.26
    - Shapely==1.6.4.post2
    - pyquaternion==0.9.5 
    - sk-video==1.1.10
