### ISSUE TITLE
Questions about running environment

### ISSUE THREAD

**Issue by qingfengtommy** [Xingyu-Lin/softgym#44]
Hi Xinyu Lin,

I appreciate your generosity in sharing the source code.

I am currently endeavoring to replicate the original datasets on a remote headless server running Linux 18.04 with Nvidia Driver, and this setup lacks physical monitors. It appears that OpenGL doesn't work in the absence of a physical screen.

Could you kindly provide more information about your server environment? Specifically, does it include a physical monitor? I am eager to determine whether it is feasible to reproduce the dataset within a screenless environment.

Best,
Tommy

**Comment by Xingyu-Lin** [comment]
Yes. Turn on EGL-based rendering with --headless=1
