### ISSUE TITLE
rope_configuration.pkl not found

### ISSUE THREAD

**Issue by ZhangHanbo** [Xingyu-Lin/softgym#8]
When I run the rope configuration env, it gives an error saying that the required rope_configuration.pkl not found.

Could you provide the rope_configuration.pkl for the rope configuration environment?

**Comment by Xingyu-Lin** [comment]
Hi ZhangHanbo, 

Sorry for the late reply. You can download the pkl following [this link](https://drive.google.com/file/d/1f3FK_7gwnJLVm3VaSacvYS7o-19-XPrr/view?usp=sharing)
